"""Bittensor Synapse protocol definitions for the Modelionn ZK prover subnet.

These define the wire format for miner ←→ validator communication
in the zero-knowledge proof generation network.
"""

from __future__ import annotations

from typing import Any

import bittensor as bt
from pydantic import Field


# ---------------------------------------------------------------------------
# 1. Proof Request — validator dispatches proof work to a prover miner
# ---------------------------------------------------------------------------

class ProofRequestSynapse(bt.Synapse):
    """Validator → Miner: generate a proof fragment for a circuit partition.

    The validator sends circuit data and a partition assignment.
    The miner generates the proof fragment using GPU acceleration and returns it.
    """

    # Request fields (validator → miner)
    job_id: str = ""
    circuit_cid: str = ""                   # IPFS CID of the circuit
    partition_index: int = 0
    total_partitions: int = 1
    constraint_start: int = 0
    constraint_end: int = 0
    witness_cid: str = ""                   # IPFS CID of the witness fragment
    proving_key_cid: str = ""               # IPFS CID of the proving key
    proof_system: str = "groth16"           # groth16 | plonk | halo2 | stark
    circuit_type: str = "general"           # general | evm | zkml | custom
    timeout_s: int = 600

    # Response fields (miner → validator)
    proof_fragment: bytes = b""             # Serialized proof fragment
    commitment: bytes = b""                 # Intermediate commitment for aggregation
    generation_time_ms: int = 0             # Actual proving time
    gpu_backend_used: str = ""              # cuda | rocm | metal | webgpu | cpu
    error: str = ""

    def deserialize(self) -> dict[str, Any]:
        return {
            "job_id": self.job_id,
            "partition_index": self.partition_index,
            "proof_fragment": self.proof_fragment,
            "commitment": self.commitment,
            "generation_time_ms": self.generation_time_ms,
            "gpu_backend_used": self.gpu_backend_used,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# 2. Capability Ping — validator queries miner GPU capabilities + health
# ---------------------------------------------------------------------------

class CapabilityPingSynapse(bt.Synapse):
    """Validator → Miner: report your GPU capabilities and current load.

    Used for prover selection, health monitoring, and benchmark scoring.
    """

    # Request
    include_benchmark: bool = False         # If True, miner runs a quick benchmark

    # Response
    gpu_name: str = ""
    gpu_backend: str = ""                   # cuda | rocm | metal | webgpu | cpu
    gpu_count: int = 0
    vram_total_bytes: int = 0
    vram_available_bytes: int = 0
    compute_units: int = 0
    compute_version: str = ""
    benchmark_score: float = 0.0            # Proofs/second on standard test circuit
    supported_proof_types: str = ""         # Comma-separated: groth16,plonk,halo2,stark
    max_constraints: int = 0
    current_load: float = 0.0               # 0.0-1.0 utilization
    total_proofs: int = 0
    successful_proofs: int = 0
    uptime_seconds: int = 0

    def deserialize(self) -> dict[str, Any]:
        return {
            "gpu_name": self.gpu_name,
            "gpu_backend": self.gpu_backend,
            "gpu_count": self.gpu_count,
            "vram_total_bytes": self.vram_total_bytes,
            "vram_available_bytes": self.vram_available_bytes,
            "compute_units": self.compute_units,
            "compute_version": self.compute_version,
            "benchmark_score": self.benchmark_score,
            "supported_proof_types": self.supported_proof_types,
            "max_constraints": self.max_constraints,
            "current_load": self.current_load,
            "total_proofs": self.total_proofs,
            "successful_proofs": self.successful_proofs,
            "uptime_seconds": self.uptime_seconds,
        }


# ---------------------------------------------------------------------------
# 3. Proof Verify — validator asks miner to verify another miner's proof
# ---------------------------------------------------------------------------

class ProofVerifySynapse(bt.Synapse):
    """Validator → Miner: verify a proof generated by another prover.

    Multi-validator consensus: multiple validators independently verify
    proof correctness. This enables binary (pass/fail) consensus.
    """

    # Request
    proof_cid: str = ""                     # IPFS CID of the proof to verify
    circuit_cid: str = ""                   # IPFS CID of the circuit
    verification_key_cid: str = ""          # IPFS CID of the verification key
    public_inputs_json: str = ""            # JSON-serialized public inputs
    proof_system: str = "groth16"

    # Response
    valid: bool = False
    verification_time_ms: int = 0
    details: str = ""
    error: str = ""

    def deserialize(self) -> dict[str, Any]:
        return {
            "valid": self.valid,
            "verification_time_ms": self.verification_time_ms,
            "details": self.details,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# 4. Commit-Reveal — anti-frontrunning for circuit submissions (preserved)
# ---------------------------------------------------------------------------

class CommitRevealSynapse(bt.Synapse):
    """Miner ↔ Validator: two-phase commit-reveal for circuit submissions."""

    # Phase: "commit" or "reveal"
    phase: str = ""

    # Commit phase fields
    artifact_name: str = ""
    commit_hash: str = ""  # SHA256(name || circuit_hash || nonce)

    # Reveal phase fields
    artifact_hash: str = ""  # SHA256 of actual content
    nonce: str = ""

    # Response
    accepted: bool = False
    is_earliest: bool = False
    error: str = ""

    def deserialize(self) -> dict[str, Any]:
        return {
            "phase": self.phase,
            "accepted": self.accepted,
            "is_earliest": self.is_earliest,
            "error": self.error,
        }
